### ISSUE TITLE
Cannot make a upgrade to Hilla 1.0.6 to work

### ISSUE THREAD

**Issue by sveine** [jcgueriaud1/vaadin-multilanguage-app#3]
Output:

![image](https://user-images.githubusercontent.com/367125/163985503-8a5c7019-3358-4f59-8969-ab5fdf198b3d.png)
(part) => {
    partCache.set(part, cb);
    updatePart(part, cb);
}

Using @NpmPackage(value = "lit-translate", version = "^2.0.0") the result is:
![image](https://user-images.githubusercontent.com/367125/163986029-2f842936-f88c-4fd8-84c5-f6ab46105ddf.png)

**Comment by jcgueriaud1** [comment]
I've updated the v23 branch to Hilla 1.0.6. It seems to work. I also updated the code to Lit 2.
https://github.com/jcgueriaud1/vaadin-multilanguage-app/tree/v23

Maybe it's a conflict between lit 1 and 2. It's hard to say without more information.

**Comment by sveine** [comment]
@jcgueriaud1 Tanks a lot for super fast reply! Forgot to look for a v23 branch - it is working!
